### ISSUE TITLE
Athena is crashing

### ISSUE THREAD

**Issue by LabRatMime** [djlorenzouasset/Athena#12]
I'm not quite sure why this is happening but when I launch athena it crashes. I've tried using the latest version and downgrading but I get the same results
[Athena-Log-12-12-2023.txt](https://github.com/djlorenzouasset/Athena/files/13655447/Athena-Log-12-12-2023.txt)

**Comment by djlorenzouasset** [comment]
this is an API problem. When you encounter this error, wait some minutes before useing the program.
