### ISSUE TITLE
Toona Fish not showing styles

### ISSUE THREAD

**Issue by min89xd** [djlorenzouasset/Athena#13]
It also happens with all his set 
![imagen_2023-12-23_130247454](https://github.com/djlorenzouasset/Athena/assets/90361729/18b87352-34f2-4f6b-a855-baf5a53e88cc)

**Comment by djlorenzouasset** [comment]
Im going to fix this problem in a next update. Keep this issue opened for now, I'll close it when solved.

**Comment by djlorenzouasset** [comment]
This issue seems game side and not from athena. I checked and variants in the profile are ok. When I have more informations I'll comment under this issue.

**Comment by max8447** [comment]
variant selection has been horrible since ch5, even on epic servers so this is no surprise

**Comment by djlorenzouasset** [comment]
> variant selection has been horrible since ch5, even on epic servers so this is no surprise

yea, probably the new UI broke some cosmetics styles

**Comment by djlorenzouasset** [comment]
This issue will be fixed for the next release.

**Comment by djlorenzouasset** [comment]
This issue has been fixed in v1.5.4
