### ISSUE TITLE
Not every car gets added to the profile when adding all cosmetics

### ISSUE THREAD

**Issue by Gentlecat2210** [djlorenzouasset/Athena#19]
![image](https://github.com/djlorenzouasset/Athena/assets/62384836/f817d208-1e0a-4e3b-b066-a4ed717f4d96)

**Comment by Gentlecat2210** [comment]
This also includes Decals and Wheels. 
![image](https://github.com/djlorenzouasset/Athena/assets/62384836/97bfba6c-c807-434d-ab5f-dc18e4f05853)
![image](https://github.com/djlorenzouasset/Athena/assets/62384836/606af0ff-012c-4344-a622-b645b314cc6b)

**Comment by djlorenzouasset** [comment]
try download the latest version of Athena. If the issue persists, please comment again under this issue and I'll take a look when possible.

**Comment by Gentlecat2210** [comment]
Profile was generated with 1.6.0
[Athena-Log-18-05-2024.txt](https://github.com/djlorenzouasset/Athena/files/15365858/Athena-Log-18-05-2024.txt)

**Comment by djlorenzouasset** [comment]
fixing this issue in a next update.

**Comment by djlorenzouasset** [comment]
This issue has been fixed in v1.7.0 #22
