### ISSUE TITLE
can you still download this in September 2024?

### ISSUE THREAD

**Issue by Laroi4life** [djlorenzouasset/Athena#21]
i was wondering if you can still download this is September 2024 because i just downloaded carbon just today and i dont know how to get skins in carbon

**Comment by djlorenzouasset** [comment]
atm, Cranium and Carbon are in a state of non functionality since v30.10 (caused by the new anticheat system). You can still get skins on old versions of the game.

**Comment by djlorenzouasset** [comment]
closing this issue.
