### ISSUE TITLE
Default cosmetics + love and thunder back blings don't get added in the profile.

### ISSUE THREAD

**Issue by LLD-Jo** [djlorenzouasset/Athena#33]
Default cosmetics + "love and thunder" set back blings don't get added in the profile.

_Pickaxe/Glider_
`AthenaPickaxe:DefaultPickaxe`
`AthenaGlider:DefaultGlider`

_Instruments_
`SparksBass:Sparks_Bass_Generic`
`SparksGuitar:Sparks_Guitar_Generic`
`SparksDrums:Sparks_Drum_Generic`
`SparksKeyboard:Sparks_Keytar_Generic`
`SparksMicrophone:Sparks_Mic_Generic`

_Love and Thunder Set Backblings_
`AthenaBackpack:BID_A_036_TrifleMale`
`AthenaBackpack:BID_A_037_ParfaitFemale`

**Comment by djlorenzouasset** [comment]
This issue will be fixed in a next update.

**Comment by djlorenzouasset** [comment]
Good evening, I just checked that create a profile with "All Cosmetics" actually add Love and Thunder backblings. For the rest, default cosmetics are missing and I'm going to release a fix in the next days.

**Comment by djlorenzouasset** [comment]
This issue has been fixed (pull #37)
