### ISSUE TITLE
New Cosmetics don't include dynamic paks

### ISSUE THREAD

**Issue by tokenspins** [djlorenzouasset/Athena#4]
Is it intended that new cosmetics don't include dynamic paks or is it a bug?

I would like it to be included or atleast have it as an option in the config.
The same thing goes for the shop catalog.

**Comment by djlorenzouasset** [comment]
I can get this as new feature. And no, is not a bug. I'll start work on it later or tomorrow and I'll push the update when ready.

**Comment by djlorenzouasset** [comment]
Issue Fixed. Now the option for add paks to new cosmetics is available.
