### ISSUE TITLE
Cosmetics can't be equipped

### ISSUE THREAD

**Issue by tokenspins** [djlorenzouasset/Athena#5]
With an athena profile generated with version 1.2.0 the cosmetics can't be equipped in the locker.
The old 1.1.0 release was working fine. I use NeoniteV2 as private server.

**Comment by djlorenzouasset** [comment]
weird issue. I'll try to see what's the problem.

**Comment by djlorenzouasset** [comment]
ok seems a problem only for you. Just tested and asked a friend to test and we actually dont have this problem. Try restart the Neonite V2 backend and try again.

**Comment by djlorenzouasset** [comment]
ok just saw, with the v1.2.0 I removed a thing from the AthenaProfile model. Fixing it now and pushing the update

**Comment by djlorenzouasset** [comment]
Issue Fixed.
